Added `raise` statement (#135)
* Added 'raise' statement

Syntax:
raise ErrorType "Error Message"

* Expressions as error messages

Things like:

raise RTError 1+1

or

msg = "Error Message"
raise TypeError msg

would work now

* New Syntax

Syntax: raise FooError("message")

* Added `raise.rn` test

* Some Bugfixes + `raise` support for only functions

Now it is only possible to raise errors with function calls
```
fun ArgError(arg)
{
    return "Argument `"+arg+"` not found"
}

raise ArgError("arg1")
```

The name of the function will also be the error type
```
ArgError: Argument `arg1` not found
```

* Updated tests

Updated `raise.rn.json` to match the new output
Removed debug line (parser.py:167)

* Some fixes

* Normalize line endings in stdout and stderr

* Some Type fixes

* Revert "Some Type fixes"

This reverts commit 6a6763d8b703d10214afb94a2751622ddb6d2bce.

* feat: handled message less error formatting.

* fix: visit_RaiseNode None message type.

* fix: optional types.

* Update parser.py

* fix: type issues.

* fix: type issues.

* fix: type error

* fix: ruff formattings.

* Update parser.py

* fix: type errors

* fix: ruff formattings.

---------

Co-authored-by: Md. Almas Ali <almaspr3@gmail.com>